---
  - name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS
    hosts: "csr1"
    connection: network_cli
    gather_facts: no
    tasks:
      - name: TASK 1 in PLAY 1 - Modifying the SNMP configuration
        cisco.ios.ios_snmp_server:
          config:
            communities:
            -   name: CLUS-DEMO
                ro: true
            contact: BEARDED_GUY
            location: LAS_VEGAS
          state: merged
      - name: "TASK 2 in PLAY 1 - Verify the SNMP configuration exists"
        cisco.ios.ios_snmp_server:
          state: gathered